@BASE_URI = http://localhost:9000/api/admin


# # Admin Registration
# POST {{BASE_URI}}/register
# Content-Type: application/json

# {
#     "name": "name",
#     "email": "email@gmail.com",
#     "password": "password",
#     "phoneNumber": 9876543210
# }

# Admin Login
# POST {{BASE_URI}}/login
# Content-Type: application/json

# {
#     "email": "email@gmail.com",
#     "password": "password"
# }