@BASE_URL = http://localhost:9000/api/categories

// user
@TOKEN = replace your token here

# Get All Categories
# GET {{BASE_URL}}/


# # Get Category By Id
# GET {{BASE_URL}}/62449f2512e142682804fe2e

# # Add Category
POST {{BASE_URL}}/
Authorization: {{TOKEN}}
Content-Type: application/json

{
    "categoryName": "Grocery",
    "categoryImage": "https://firebasestorage.googleapis.com/v0/b/city-super-market.appspot.com/o/grocery%2Fimage?alt=media&token=60d4ad26-7515-4d12-9bf8-b81957a01060",
    "subCategoryList": [
      "soaps and detergents",
      "Coffee and tea powders",
      "floor and bathroom cleaning items",
      "Water bottles "
    ]
}