@BASE_URL = http://localhost:9000/api/products

@TOKEN = replace your token here

# # Get All products
# GET {{BASE_URL}}/

# # Get Products by ID
# GET {{BASE_URL}}/648ef8d3815d297495cb555e

# # Add Product
# POST {{BASE_URL}}/
# Authorization: {{TOKEN}}
# Content-Type: application/json

# {
#     "productId":"1002",
#     "categoryId": "64bd7a3f3b672888d6a3c4d8",
#     "subCategory": "Coffee and tea powders",
#     "image": "https://firebasestorage.googleapis.com/v0/b/city-super-market.appspot.com/o/Fooddrinkssprite%2Fimage?alt=media&token=71e17890-0129-4e23-b755-ebb5cebfe011",
#     "brand": "Red label",
#     "name": "Red label coffe powder",
#     "variants": [
#         {
#             "price": 50,
#             "quantity": 500,
#             "isSpecialOffer":false,
#             "discount":30
#         },
#         {
#             "price": 25,
#             "quantity": 250,
#             "isSpecialOffer":false,
#             "discount":5
#         },
#         {
#             "price": 300,
#             "quantity": 1000,
#             "isSpecialOffer":false,
#             "discount":100
#         }
#     ],
#     "quantityType": "g",
#     "description": "Red label coffee powder"
# }

# Get Top Products by Category
# GET {{BASE_URL}}/topProductsByCategory/2

# Get Products by Category
GET {{BASE_URL}}/category/64bd7a3f3b672888d6a3c4d8
