@BASE_URL = http://localhost:9000/api/products

@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGUyMmVmYjBiOTRjYzRlODMzN2JhYiIsIm5hbWUiOiJEaGFtYXJlc2h3YXJha3VtYXIiLCJlbWFpbCI6ImRhbWFyZXNod2FyYWt1bWFyQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsInBob25lTnVtYmVyIjoiNzY2MTk3OTk0MyIsImlhdCI6MTY4NzA5MTMwNiwiZXhwIjoxNjg3MDk0OTA2fQ.t05NSSY6H5WjOjsExK_KUhCFXNkkC0jraKQhQ4-jgCo

# # Get All products
# GET {{BASE_URL}}/

# # Get Products by ID
# GET {{BASE_URL}}/648ef8d3815d297495cb555e

# # Add Product
# POST {{BASE_URL}}/
# Authorization: {{TOKEN}}
# Content-Type: application/json

# {
#     "categoryId": "648ef19b18e0ca329961acdd",
#     "subCategory": "Drinks",
#     "image": "https://firebasestorage.googleapis.com/v0/b/city-super-market.appspot.com/o/Fooddrinkssprite%2Fimage?alt=media&token=71e17890-0129-4e23-b755-ebb5cebfe011",
#     "brand": "test",
#     "name": "test",
#     "variants": [
#         {
#             "price": 100,
#             "quantity": 1
#         },
#         {
#             "price": 200,
#             "quantity": 2
#         },
#         {
#             "price": 300,
#             "quantity": 3
#         }
#     ],
#     "quantityType": "unit"
# }

# Get Products by Category
GET {{BASE_URL}}/topProductsByCategory/2