@BASE_URI = http://localhost:9000/api

@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGVjN2RlNDE1YTk4ZGQzYjVjNmMyMyIsIm5hbWUiOiJQcmF0aHl1c2hhIFBhZG1hbmFiaHVuaSIsImVtYWlsIjoiIiwiaXNBZG1pbiI6ZmFsc2UsInBob25lTnVtYmVyIjoiNzY2MTk3OTk0MSIsImlhdCI6MTY4NzEyMzkxMSwiZXhwIjoxNjg3MTI3NTExfQ.YnL2ObLYlpZOHsPKVnzr9Q01v4M8xlcvr8Fn0IBSbmY

# # Get all users
# GET {{BASE_URI}}/users
# Authorization: {{TOKEN}}

# # Get user by id
# GET {{BASE_URI}}/users/648ec7de415a98dd3b5c6c23
# Authorization: {{TOKEN}}

# # User Registration
# POST {{BASE_URI}}/users
# Content-Type: application/json

# {
#     "name": "Prathyusha",
#     "email": "prathyusha@gmail.com",
#     "password": "123456",
#     "phoneNumber": "7661979941"
# }

# # User Login
# POST {{BASE_URI}}/users/login
# Content-Type: application/json

# {
#     "phoneNumber": "7661979941",
#     "password": "12345678"
# }


# # Update user
# PUT {{BASE_URI}}/users/648ec7de415a98dd3b5c6c23
# Authorization: {{TOKEN}}
# Content-Type: application/json

# {
#     "name": "Prathyusha Padmanabhuni",
#     "password": "12345678",
#     "email": "prathyu@gmail.com",
#     "address": [{
#         "doorNumber": "1-2-3/4",
#         "streetName": "KPHB 5th Phase",
#         "village": "KPHB",
#         "mandal": "Kukatpally",
#         "pincode": "500081"
#     }]
# }