@BASE_URI = http://localhost:9000/api

@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGUyMmVmYjBiOTRjYzRlODMzN2JhYiIsIm5hbWUiOiJEaGFtYXJlc2h3YXJha3VtYXIiLCJlbWFpbCI6ImRhbWFyZXNod2FyYWt1bWFyQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsInBob25lTnVtYmVyIjoiNzY2MTk3OTk0MyIsImlhdCI6MTY4NzA4NDQ2OSwiZXhwIjoxNjg3MDg4MDY5fQ.qCrFo4M9rFBTvQTZAh0FPUaA48r_DieuoKFWywUnpyg

# Get all users
GET {{BASE_URI}}/users
Authorization: {{TOKEN}}

# # Get user by id
# GET {{BASE_URI}}/users/648e318395875f34a00a20cf
# Authorization: {{TOKEN}}

# # User Registration
# POST {{BASE_URI}}/users
# Content-Type: application/json

# {
#     "name": "Prathyusha",
#     "email": "prathyusha@gmail.com",
#     "password": "123456",
#     "phoneNumber": "7661979941"
# }

# # User Login
# POST {{BASE_URI}}/users/login
# Content-Type: application/json

# {
#     "phoneNumber": "7661979941",
#     "password": "123456"
# }
