@BASE_URI = http://localhost:9000/api

@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGUzMTgzOTU4NzVmMzRhMDBhMjBjZiIsIm5hbWUiOiJEaGFtcmVzaHdhcmFrdW1hciIsImVtYWlsIjoiIiwiaXNBZG1pbiI6ZmFsc2UsInBob25lTnVtYmVyIjoiNzY2MTk3OTk0MiIsImlhdCI6MTY4NzA3ODgwNywiZXhwIjoxNjg3MDgyNDA3fQ.4Xg8wslUGesxGeWTRp-wYK_-6Yl4Y1i8WFvxEtYV3Nc

# # Get all users
# GET {{BASE_URI}}/users
# Authorization: {{TOKEN}}

# # Get user by id
# GET {{BASE_URI}}/users/648e318395875f34a00a20cf
# Authorization: {{TOKEN}}

# # User Registration
# POST {{BASE_URI}}/users
# Content-Type: application/json

# {
#     "name": "Prathyusha",
#     "email": "prathyusha@gmail.com",
#     "password": "123456",
#     "phoneNumber": "7661979941"
# }

# # User Login
# POST {{BASE_URI}}/users/login
# Content-Type: application/json

# {
#     "phoneNumber": "7661979941",
#     "password": "123456"
# }
